# Generated by Django 2.2.13 on 2020-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='checksum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='version',
            name='checksum_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='version',
            name='checksum_x64',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='version',
            name='checksum_x86',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='version',
            name='dllink',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='version',
            name='dllink_x64',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='version',
            name='dllink_x86',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='version',
            name='lastupdated',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
