# Generated by Django 2.2.10 on 2020-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='lastupdated',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='version',
            name='checksum',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='version',
            name='checksum_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='version',
            name='checksum_x64',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='version',
            name='checksum_x86',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='version',
            name='dllink',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='version',
            name='dllink_x64',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='version',
            name='dllink_x86',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
